db_postgres:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: "tomirubinstein@gmail.com"
      password: "airbyte"
      dbname: mlops
      schema: source
      threads: 1
